spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://ebik-rds-mysql-db.c4u1nmtys1wu.us-east-1.rds.amazonaws.com:3306/ebik?serverTimezone=UTC
    username: ebik
    password: 'passwordebik'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
  http:
    multipart:
      max-file-size: 5MB

logging:
  level:
    org:
      hibernate:
        type: trace

cloud:
  aws:
    credentials:
      accessKey: ""
      secreteKey: ""
      region: "us-east-1"

jwt:
  securityKey: 'securesecuresecurehbsfljjkdwnlDWscjkcfbkt8322yroyo823ye29ogdiqeo2y282u7g2d28u2fwiut821yw'
  tokenPrefix: 'Bearer'
  expirationAfterDays: 14

server:
  port: 5000