POST http://localhost:8080/ebik/car/register_new_car
Content-Type: application/json

[
  {
    "brand": "Toyota",
    "model": "Tacoma SR5",
    "bodyStyle": "Truck",
    "year": 2019
  },
  {
    "brand": "Nissa",
    "model": "Frontier RPO-x",
    "bodyStyle": "Truck",
    "year": 2019
  },
  {
    "brand": "Nissa",
    "model": "Frontier RPO-x",
    "bodyStyle": "Truck",
    "year": 2022
  },
  {
    "brand": "Toyota",
    "model": "Camry XSE",
    "bodyStyle": "Sedan",
    "year": 2016
  },
  {
    "brand": "Nissa",
    "model": "Altima SR",
    "bodyStyle": "SV",
    "year": 2017
  },
  {
    "brand": "Nissa",
    "model": "Altima",
    "bodyStyle": "SV",
    "year": 2020
  },
  {
    "brand": "Nissa",
    "model": "Altima SL",
    "bodyStyle": "SV",
    "year": 2015
  },
  {
    "brand": "Toyota",
    "model": "Tacoma SR5",
    "bodyStyle": "Truck",
    "year": 2017
  },
  {
    "brand": "Toyota",
    "model": "Corolla LE",
    "bodyStyle": "Sedan",
    "year": 2018
  },
  {
    "brand": "Toyota",
    "model": "Camry XSE",
    "bodyStyle": "SV",
    "year": 2020
  },
  {
    "brand": "Ford",
    "model": "Ranger XLT",
    "bodyStyle": "Truck",
    "year": 2021
  },
  {
    "brand": "Toyota",
    "model": "Tacoma SR5",
    "bodyStyle": "Truck",
    "year": 2019
  },
  {
    "brand": "Ford",
    "model": "Escape SEL",
    "bodyStyle": "SUV",
    "year": 2021
  },
  {
    "brand": "Nissan",
    "model": "Maxima",
    "bodyStyle": "SV",
    "year": 2021
  },
  {
    "brand": "Ford",
    "model": "EcoSport SE",
    "bodyStyle": "SUV",
    "year": 2010
  },
  {
    "brand": "Nissan",
    "model": "Altima SR",
    "bodyStyle": "Sedan",
    "year": 2018
  },
  {
    "brand": "Nissan",
    "model": "Altima",
    "bodyStyle": "SR",
    "year": 2018
  },
  {
    "brand": "Toyota",
    "model": "Corolla LE",
    "bodyStyle": "Sedan",
    "year": 2021
  },
  {
    "brand": "Toyota",
    "model": "Corolla LE",
    "bodyStyle": "Sedan",
    "year": 2014
  }
]