POST http://localhost:8080/ebik/checkout/checkout
Content-Type: application/json

{
  "carCheckOut": {
    "vin": 155296945,
    "brand": "Toyota",
    "model": "Camry XSE",
    "bodyStyle": "Sedan",
    "year": 2016
  }
}