POST http://localhost:8080/ebik/driver/add_new_driver
Content-Type: application/json;charset=UTF-8

//{
//  "driverID": 5462781,
//  "firstName": "Ashely",
//  "lastName": "More",
//  "email": "ashelymore56@gmail.com",
//  "phoneNum": "6735147890",
//  "address": [
//    {
//      "addressID": 7463626881,
//      "street": "5422 Drive street NW",
//      "city": "Charlotte",
//      "state": "NC",
//      "zipcode": 28734
//    }
//  ]
//}

//{
//  "driverID": 5462781,
//  "firstName": "Fayanga",
//  "lastName": "Keita",
//  "email": "fayangakei@gmail.com",
//  "phoneNum": "1116667800",
//  "address": [
//    {
//      "street": "7632 King Drive",
//      "city": "Grand Rapid",
//      "state": "MI",
//      "zipcode": 67234
//    }
//  ]
//}

{
  "driverID": 5462781,
  "firstName": "John",
  "lastName": "Robert",
  "email": "robert65@gmail.com",
  "phoneNum": "8937650012",
  "address": [
    {
      "street": "782 Roanoke Ave NE",
      "city": "Grand Rapid",
      "state": "MI",
      "zipcode": 89342
    }
  ]
}


